apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-webhook-paneldns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-webhook-paneldns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cert-manager-webhook-paneldns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-manager-webhook-paneldns.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "cert-manager-webhook-paneldns.fullname" . }}-webhook-tls
